/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.jeu;

import java.util.Timer;

/**
 *
 * @author jeann
 */
public class fenetreJeu extends javax.swing.JFrame {

    String Joueur1;
    Grille GrilleJeu = new Grille();
    Timer chrono = new Timer();
    boolean clique=false;
    int tour=0;

    /**
     * Creates new form fenetreJeu
     */
    public fenetreJeu() {
        
        initComponents();
        
        panneau_grille.setVisible(false); 
        panneau_creationpartie.setVisible(false); // on cache ces 2 panneaux avant 
        // début de la partie
        panneauinfopartie.setVisible(false);

        for (int i = 5; i >= 0; i--) { // crée 36 cellules graphiques
            for (int j = 0; j < 6; j++) {
                BoutonGraphique boutgraph = new BoutonGraphique(GrilleJeu.GrillePartie[i][j]);
                panneau_grille.add(boutgraph);
                 boutgraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Bouton b = boutgraph.boutonassociee;

                        if (b.boutonAllume == false) {
                            return;
                        } 
                        else if (b.Couleur.equals("coronavirus") )  {
                            b.EteindreLeBouton();
                            clique = true;
                            tour++;
                            label_nbrecoups.setText(tour + "");
                            
                            
                            for (int i = 0; i < 7; i++) {
                                for (int j = 0; j < 7; j++) {
                                    if (GrilleJeu.GrillePartie[i][j].Couleur.equals("masque") || GrilleJeu.GrillePartie[i][j].Couleur.equals("delta") ) {
                                        GrilleJeu.GrillePartie[i][j].EteindreLeBouton();
                                    }
                                }
                            }
                            
                            jouer();
                        }
                        
                        else if (b.Couleur.equals("masque") ) {
                            b.EteindreLeBouton();
                            tour--;
                            label_nbrecoups.setText(tour + "");
                                                       
                            for (int i = 0; i < 7; i++) {
                                for (int j = 0; j < 7; j++) {
                                    if (GrilleJeu.GrillePartie[i][j].Couleur.equals("coronavirus") || GrilleJeu.GrillePartie[i][j].Couleur.equals("delta")) {
                                        GrilleJeu.GrillePartie[i][j].EteindreLeBouton();
                                    }
                                }
                            }
                            jouer();
                        }
                        
                        else if (b.Couleur.equals("delta") ) { 
                            b.EteindreLeBouton();
                            tour= tour + 2;
                            label_nbrecoups.setText(tour + "");
                            panneau_grille.repaint();
                            for (int i = 0; i < 7; i++) {
                                for (int j = 0; j < 7; j++) {
                                    if (GrilleJeu.GrillePartie[i][j].Couleur.equals("coronavirus") || GrilleJeu.GrillePartie[i][j].Couleur.equals("masque")) {
                                        GrilleJeu.GrillePartie[i][j].EteindreLeBouton();
                                    }
                                }
                            }
                            jouer();
                        }
            }
            
        });
                
        
        
    }}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_infojoueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomJoueur = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_creationpartie = new javax.swing.JPanel();
        label_nbrecoups = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panneauinfopartie = new javax.swing.JPanel();
        labelTemps = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadre_bienvenue = new javax.swing.JPanel();
        btn_bienv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 6));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 576, 576));

        panneau_infojoueur.setBackground(new java.awt.Color(204, 255, 255));
        panneau_infojoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur :");
        panneau_infojoueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));
        panneau_infojoueur.add(nomJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 30));

        btn_start.setText("Let's go kick some corona");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_infojoueur.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 50));

        getContentPane().add(panneau_infojoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 260, 200));

        panneau_creationpartie.setBackground(new java.awt.Color(204, 255, 255));
        panneau_creationpartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nbrecoups.setText("nbrcoups");
        panneau_creationpartie.add(label_nbrecoups, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 50));

        jLabel5.setText("Score :");
        panneau_creationpartie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        getContentPane().add(panneau_creationpartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 260, 100));

        panneauinfopartie.setBackground(new java.awt.Color(204, 255, 255));
        panneauinfopartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTemps.setText("tps_restant");
        panneauinfopartie.add(labelTemps, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 50));

        jLabel3.setText("Temps restatnt :");
        panneauinfopartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 50));

        getContentPane().add(panneauinfopartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 260, 180));

        cadre_bienvenue.setBackground(new java.awt.Color(204, 204, 255));

        btn_bienv.setText("Bienvenue");
        btn_bienv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bienvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadre_bienvenueLayout = new javax.swing.GroupLayout(cadre_bienvenue);
        cadre_bienvenue.setLayout(cadre_bienvenueLayout);
        cadre_bienvenueLayout.setHorizontalGroup(
            cadre_bienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadre_bienvenueLayout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(btn_bienv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        cadre_bienvenueLayout.setVerticalGroup(
            cadre_bienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadre_bienvenueLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_bienv)
                .addContainerGap(596, Short.MAX_VALUE))
        );

        getContentPane().add(cadre_bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 980, 640));

        setBounds(0, 0, 997, 688);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_creationpartie.setVisible(true); // quand bouton est cliquer
        // affichage des 2 panneaux
        panneauinfopartie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint(); // permet de redessiner la grille
        btn_start.setEnabled(false); // permet de désactiver le bouton "start"
        labelTemps.setText("start"); // le chrono démare
        
        //labelTemps.addActionListener(new java.awt.event.ActionListener()) {
        //public vo
                
             
                
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_bienvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bienvActionPerformed
        panneau_grille.setVisible(true);
        btn_bienv.setVisible(false);
    }//GEN-LAST:event_btn_bienvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreJeu().setVisible(true);
            }
        });
    }


public void initialiserPartie(){
    String nomJoueur1 = nomJoueur.getText();
    GrilleJeu.BoutonAleatoirementAllume();
    
    //labelTemps.set
}


  public void jouer() {
        GrilleJeu.BoutonAleatoirementAllume();
        panneau_grille.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bienv;
    private javax.swing.JButton btn_start;
    private javax.swing.JPanel cadre_bienvenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelTemps;
    private javax.swing.JLabel label_nbrecoups;
    private javax.swing.JTextField nomJoueur;
    private javax.swing.JPanel panneau_creationpartie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infojoueur;
    private javax.swing.JPanel panneauinfopartie;
    // End of variables declaration//GEN-END:variables
}
